export const RES_LIST_ISSUES_CATEGORY = "RES_LIST_ISSUES_CATEGORY";
export const RES_CREATE_ISSUE = "RES_CREATE_ISSUE";
export const RES_GET_REQUEST_DETAILS = "RES_GET_REQUEST_DETAILS";
export const SET_ISSUES_ATTACHMENTS = "SET_ISSUES_ATTACHMENTS";
export const DELETE_ISSUE_ATTACHMENT = "DELETE_ISSUE_ATTACHMENT";
export const SET_ISSUE_CARD_ITEM = "SET_ISSUE_CARD_ITEM";
