export const INIT_MODEL = "INIT_MODEL";
export const MODEL_CHANGE_START = "MODEL_CHANGE_START";
export const MODEL_CHANGE_END = "MODEL_CHANGE_END";
export const TASK_CHANGE_END = "TASK_CHANGE_END";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CHANGE_ADMIN_TABLE_PAGE = "CHANGE_ADMIN_TABLE_PAGE";
export const SET_USER_ROLE_LIST = "SET_USER_ROLE_LIST";
export const SET_USER_ROLE_LIST_UPDATE = "SET_USER_ROLE_LIST_UPDATE";
export const USER_UPDATE_DATA = "USER_UPDATE_DATA";
